fixtures:
  repositories:
  symlinks:
    proxysql: "#{source_dir}"
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.11.0'
    mysql:
      repo: 'puppetlabs/mysql'
      ref: '3.10.0'
